<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MWV3G0lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MWV3G0l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MWV3G0l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'velo' => ['privates', '.errored..service_locator.MWV3G0l.App\\Entity\\Velo', NULL, 'Cannot autowire service ".service_locator.MWV3G0l": it needs an instance of "App\\Entity\\Velo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'velo' => 'App\\Entity\\Velo',
        ]);
    }
}
