<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VKT6UORService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VKT6UOR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VKT6UOR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'veloType' => ['privates', '.errored..service_locator.VKT6UOR.App\\Entity\\VeloType', NULL, 'Cannot autowire service ".service_locator.VKT6UOR": it needs an instance of "App\\Entity\\VeloType" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'veloType' => 'App\\Entity\\VeloType',
        ]);
    }
}
