<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QW6vDZOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QW6vDZO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QW6vDZO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'knpSnappyPdf' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
            'reservationvelo' => ['privates', '.errored..service_locator.QW6vDZO.App\\Entity\\Reservationvelo', NULL, 'Cannot autowire service ".service_locator.QW6vDZO": it needs an instance of "App\\Entity\\Reservationvelo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'knpSnappyPdf' => '?',
            'reservationvelo' => 'App\\Entity\\Reservationvelo',
        ]);
    }
}
