<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MRz12nIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MRz12nI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MRz12nI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'covoiturage' => ['privates', '.errored..service_locator.MRz12nI.App\\Entity\\Covoiturage', NULL, 'Cannot autowire service ".service_locator.MRz12nI": it needs an instance of "App\\Entity\\Covoiturage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'covoiturage' => 'App\\Entity\\Covoiturage',
        ]);
    }
}
