<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PK3RmhOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pK3RmhO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pK3RmhO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'station' => ['privates', '.errored..service_locator.pK3RmhO.App\\Entity\\Stationvelo', NULL, 'Cannot autowire service ".service_locator.pK3RmhO": it needs an instance of "App\\Entity\\Stationvelo" but this type has been excluded in "config/services.yaml".'],
            'veloRepository' => ['privates', 'App\\Repository\\VeloRepository', 'getVeloRepositoryService', true],
        ], [
            'station' => 'App\\Entity\\Stationvelo',
            'veloRepository' => 'App\\Repository\\VeloRepository',
        ]);
    }
}
