<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5WqLUK6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5WqLUK6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5WqLUK6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'vehicule' => ['privates', '.errored..service_locator.5WqLUK6.App\\Entity\\Vehicule', NULL, 'Cannot autowire service ".service_locator.5WqLUK6": it needs an instance of "App\\Entity\\Vehicule" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'vehicule' => 'App\\Entity\\Vehicule',
        ]);
    }
}
