<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LoV_RygService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LoV.Ryg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LoV.Ryg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'station' => ['privates', '.errored..service_locator.LoV.Ryg.App\\Entity\\Stationvelo', NULL, 'Cannot autowire service ".service_locator.LoV.Ryg": it needs an instance of "App\\Entity\\Stationvelo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'station' => 'App\\Entity\\Stationvelo',
        ]);
    }
}
