<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4WB3Mu8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4WB3Mu8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4WB3Mu8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stationveloRepository' => ['privates', 'App\\Repository\\StationveloRepository', 'getStationveloRepositoryService', true],
        ], [
            'stationveloRepository' => 'App\\Repository\\StationveloRepository',
        ]);
    }
}
