<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PwM9dbpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PwM9dbp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PwM9dbp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'covoiturageRepository' => ['privates', 'App\\Repository\\CovoiturageRepository', 'getCovoiturageRepositoryService', true],
        ], [
            'covoiturageRepository' => 'App\\Repository\\CovoiturageRepository',
        ]);
    }
}
