<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationvelo3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ea1GUbP.App\Entity\Reservationvelo' shared service.
     *
     * @return \App\Entity\Reservationvelo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ea1GUbP": it needs an instance of "App\\Entity\\Reservationvelo" but this type has been excluded in "config/services.yaml".');
    }
}
