<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStationveloService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LoV.Ryg.App\Entity\Stationvelo' shared service.
     *
     * @return \App\Entity\Stationvelo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LoV.Ryg": it needs an instance of "App\\Entity\\Stationvelo" but this type has been excluded in "config/services.yaml".');
    }
}
