<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeloService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MWV3G0l.App\Entity\Velo' shared service.
     *
     * @return \App\Entity\Velo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MWV3G0l": it needs an instance of "App\\Entity\\Velo" but this type has been excluded in "config/services.yaml".');
    }
}
