<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeloType3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c4Did7D.App\Entity\VeloType' shared service.
     *
     * @return \App\Entity\VeloType
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.c4Did7D": it needs an instance of "App\\Entity\\VeloType" but this type has been excluded in "config/services.yaml".');
    }
}
