<?php

namespace ContainerXVa6Nwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\WeatherService' shared autowired service.
     *
     * @return \App\Service\WeatherService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'WeatherService.php';

        return $container->privates['App\\Service\\WeatherService'] = new \App\Service\WeatherService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
