<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Stationvelo extends \App\Entity\Stationvelo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'gouvernera' => [parent::class, 'gouvernera', null, 16],
        "\0".parent::class."\0".'id_station' => [parent::class, 'id_station', null, 16],
        "\0".parent::class."\0".'municapilite' => [parent::class, 'municapilite', null, 16],
        "\0".parent::class."\0".'name_station' => [parent::class, 'name_station', null, 16],
        "\0".parent::class."\0".'station_image' => [parent::class, 'station_image', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        "\0".parent::class."\0".'velos' => [parent::class, 'velos', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'gouvernera' => [parent::class, 'gouvernera', null, 16],
        'id_station' => [parent::class, 'id_station', null, 16],
        'lat' => [parent::class, 'lat', null, 4],
        'lon' => [parent::class, 'lon', null, 4],
        'municapilite' => [parent::class, 'municapilite', null, 16],
        'name_station' => [parent::class, 'name_station', null, 16],
        'station_image' => [parent::class, 'station_image', null, 16],
        'user' => [parent::class, 'user', null, 16],
        'velos' => [parent::class, 'velos', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
