<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'bloque' => [parent::class, 'bloque', null, 16],
        "\0".parent::class."\0".'covoiturages' => [parent::class, 'covoiturages', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'first_name' => [parent::class, 'first_name', null, 16],
        "\0".parent::class."\0".'gouvernorat' => [parent::class, 'gouvernorat', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'is_verified' => [parent::class, 'is_verified', null, 16],
        "\0".parent::class."\0".'last_name' => [parent::class, 'last_name', null, 16],
        "\0".parent::class."\0".'municipalite' => [parent::class, 'municipalite', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'phone_number' => [parent::class, 'phone_number', null, 16],
        "\0".parent::class."\0".'reservationCovs' => [parent::class, 'reservationCovs', null, 16],
        "\0".parent::class."\0".'reservationTaxis' => [parent::class, 'reservationTaxis', null, 16],
        "\0".parent::class."\0".'reservationVelos' => [parent::class, 'reservationVelos', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'stationvelos' => [parent::class, 'stationvelos', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'vehicules' => [parent::class, 'vehicules', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'bloque' => [parent::class, 'bloque', null, 16],
        'covoiturages' => [parent::class, 'covoiturages', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'first_name' => [parent::class, 'first_name', null, 16],
        'gouvernorat' => [parent::class, 'gouvernorat', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'is_verified' => [parent::class, 'is_verified', null, 16],
        'last_name' => [parent::class, 'last_name', null, 16],
        'municipalite' => [parent::class, 'municipalite', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'phone_number' => [parent::class, 'phone_number', null, 16],
        'reservationCovs' => [parent::class, 'reservationCovs', null, 16],
        'reservationTaxis' => [parent::class, 'reservationTaxis', null, 16],
        'reservationVelos' => [parent::class, 'reservationVelos', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'stationvelos' => [parent::class, 'stationvelos', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'vehicules' => [parent::class, 'vehicules', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
