<?php

namespace Container0H958xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7rcN0WtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7rcN0Wt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7rcN0Wt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationveloRepository' => ['privates', 'App\\Repository\\ReservationveloRepository', 'getReservationveloRepositoryService', true],
        ], [
            'reservationveloRepository' => 'App\\Repository\\ReservationveloRepository',
        ]);
    }
}
