<?php

namespace Container0H958xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DuP834IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DuP834I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DuP834I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationCovRepository' => ['privates', 'App\\Repository\\ReservationCovRepository', 'getReservationCovRepositoryService', true],
        ], [
            'reservationCovRepository' => 'App\\Repository\\ReservationCovRepository',
        ]);
    }
}
