<?php

namespace Container0H958xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U9bd3eGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u9bd3eG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u9bd3eG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'veloTypeRepository' => ['privates', 'App\\Repository\\VeloTypeRepository', 'getVeloTypeRepositoryService', true],
        ], [
            'veloTypeRepository' => 'App\\Repository\\VeloTypeRepository',
        ]);
    }
}
