<?php

namespace Container0H958xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CK6SRWBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CK6SRWB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CK6SRWB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationTaxi' => ['privates', '.errored..service_locator.CK6SRWB.App\\Entity\\ReservationTaxi', NULL, 'Cannot autowire service ".service_locator.CK6SRWB": it needs an instance of "App\\Entity\\ReservationTaxi" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservationTaxi' => 'App\\Entity\\ReservationTaxi',
        ]);
    }
}
