<?php

namespace Container0H958xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LsCEVVcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LsCEVVc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LsCEVVc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservationCov' => ['privates', '.errored..service_locator.LsCEVVc.App\\Entity\\ReservationCov', NULL, 'Cannot autowire service ".service_locator.LsCEVVc": it needs an instance of "App\\Entity\\ReservationCov" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'reservationCov' => 'App\\Entity\\ReservationCov',
        ]);
    }
}
