<?php

namespace Container0H958xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationCov2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Xgf1_E..App\Entity\ReservationCov' shared service.
     *
     * @return \App\Entity\ReservationCov
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Xgf1_E.": it needs an instance of "App\\Entity\\ReservationCov" but this type has been excluded in "config/services.yaml".');
    }
}
