<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container81owIsc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container81owIsc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container81owIsc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container81owIsc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container81owIsc\App_KernelDevDebugContainer([
    'container.build_hash' => '81owIsc',
    'container.build_id' => 'a60b9a47',
    'container.build_time' => 1745879278,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container81owIsc');
