<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWYGKFXx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWYGKFXx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWYGKFXx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWYGKFXx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWYGKFXx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WYGKFXx',
    'container.build_id' => '818ba2e0',
    'container.build_time' => 1745777139,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWYGKFXx');
